# ##########################################################
# Package

[package]

authors = [
	"Harry Wilson <hwils2019@gmail.com>",
	"Matt Wilson <matthew@synesis.com.au>",
]
categories = [
	"algorithms",
	"development-tools::profiling",
]
description = "Low-cost generation of performance percentiles (p50, p90, p99, etc.)"
documentation = "https://docs.rs/p99"
edition = "2021"
homepage = "https://github.com/synesissoftware/p99.Rust"
keywords = [
	"latency",
	"metrics",
	"performance",
	"percentiles",
]
license = "BSD-3-Clause"
name = "p99"
readme = "README.md"
repository = "https://github.com/synesissoftware/p99.Rust"
rust-version = "1.74"
version = "0.0.3"

[package.metadata.docs.rs]
all-features = true


# ##########################################################
# Targets

[lib]
name = "p99"
path = "src/lib.rs"

[[bench]]
name = "histogram"
harness = false

[[example]]
name = "build_histogram"
path = "examples/build_histogram.rs"


# ##########################################################
# Features

[features]

default = [
]

# General features:
#
# - "null-feature" - a feature that has no effect (and, thus, is useful for simplifying driver scripts);

null-feature = []

# Crate-specific features:
#
# - "binary-scaling" - uses binary scaling to calculate target rank, achieving higher performance with a small loss of accuracy;


binary-scaling = [
]


# ##########################################################
# Dependencies

[dependencies]


[dev-dependencies]

# 3rd-party dependencies:
#

criterion = { version = "0.8", default-features = false, features = [
] }
test_help-rs = { version = "0.2.1", default-features = false, features = [
] }


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
